//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stf.Utilities.TestResultHtmlLogger.Properties {
    using System.CodeDom.Compiler;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Diagnostics.CodeAnalysis;
    using System.Drawing;
    using System.Globalization;
    using System.Resources;
    using System.Runtime.CompilerServices;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("Stf.Utilities.TestResultHtmlLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icon_done {
            get {
                object obj = ResourceManager.GetObject("icon_done", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icon_eye {
            get {
                object obj = ResourceManager.GetObject("icon_eye", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icon_fail {
            get {
                object obj = ResourceManager.GetObject("icon_fail", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icon_right_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_right_arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap icon_star {
            get {
                object obj = ResourceManager.GetObject("icon_star", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var lastAnchor = &apos;&apos;;
        ///
        ///function getURLParameter(name) {
        ///  return decodeURIComponent((new RegExp(&apos;[?|&amp;]&apos; + name + &apos;=&apos; + &apos;([^&amp;;]+?)(&amp;|#|;|$)&apos;).exec(location.search)||[,&quot;&quot;])[1].replace(/\+/g, &apos;%20&apos;))||null
        ///}
        ///
        ///function toggleKeyValues() {
        ///	if (document.getElementById(&quot;toggleKeyValues&quot;).value == &quot;Hide&quot;) {
        ///		css(&apos;ul#logfileinfo&apos;, &apos;display&apos;, &apos;none&apos;);
        ///		toggleButton(&quot;toggleKeyValues&quot;, &quot;Show&quot;, &quot;Show KeyValues&quot;);
        ///	} else if (document.getElementById(&quot;toggleKeyValues&quot;).value == &quot;Show&quot;) {
        ///		var headerHeight =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap middot {
            get {
                object obj = ResourceManager.GetObject("middot", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body onload=&quot;loadKeyValueList()&quot;&gt;
        ///	&lt;div id=&quot;header&quot;&gt;
        ///		&lt;div id=&quot;logo&quot;&gt;&lt;/div&gt;
        ///		&lt;h1 id=&quot;logtitle&quot;&gt;LOGFILETITLE&lt;/h1&gt;
        ///		&lt;p id=&quot;generatedbypOvid&quot;&gt;Leveret til dig af Ovid&lt;/p&gt;
        ///		&lt;div id=&quot;buttons&quot;&gt;
        ///			&lt;button id=&quot;passBtn&quot;          value=&quot;Hide&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.pass&apos;,  &apos;passBtn&apos;,  &apos;Pass&apos;)&quot; &gt;Hide Pass&lt;/button&gt;
        ///			&lt;button id=&quot;failBtn&quot;          value=&quot;Hide&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.fail&apos;,  &apos;failBtn&apos;,  &apos;Fail&apos;)&quot; &gt;Hide Fail&lt;/button&gt;
        ///			&lt;button id=&quot;errorBtn&quot;         val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenBody {
            get {
                return ResourceManager.GetString("OpenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///font-family: verdana;
        ///font-size: 1.0em;
        ///color: black;
        ///padding: 0;
        ///margin: 0;
        ///}
        ///h1#logtitle {
        ///font-size: 1.5em;
        ///margin-bottom: 0px;
        ///padding-bottom: 0px;
        ///}
        ///div#logo {
        ///margin-left: 5px;
        ///height: 30px;
        ///width: 101px;
        ///background: url(data:image/x-png;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxQTEhUUExQWFhUWGBsYGBgYGBwfGhoYFx0aFxgYGx0bHiggHRolHBoYIjEiJSkrLi4uGh8zODMtNyguLisBCgoKDQ0MDwwMDiwZFBksKzcsKyssKys3KysrLCssKysrNysrKywrKywrKysrLCsrLCssKysrKyssKysrKywrK//AABEIAMIBAwMBIgACEQEDEQH/xAAbAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
