//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestResultHtmlLogger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestResultHtmlLogger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_done {
            get {
                object obj = ResourceManager.GetObject("icon_done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_eye {
            get {
                object obj = ResourceManager.GetObject("icon_eye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_fail {
            get {
                object obj = ResourceManager.GetObject("icon_fail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_right_arrow {
            get {
                object obj = ResourceManager.GetObject("icon_right_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_star {
            get {
                object obj = ResourceManager.GetObject("icon_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var lastAnchor = &apos;&apos;;
        ///
        ///
        ///function getURLParameter(name) {
        ///  return decodeURIComponent((new RegExp(&apos;[?|&amp;]&apos; + name + &apos;=&apos; + &apos;([^&amp;;]+?)(&amp;|#|;|$)&apos;).exec(location.search)||[,&quot;&quot;])[1].replace(/\+/g, &apos;%20&apos;))||null
        ///}
        ///
        ///function toggleKeyValues() {
        ///	if (document.getElementById(&quot;toggleKeyValues&quot;).value == &quot;Skjul&quot;) {
        ///		css(&apos;ul#logfileinfo&apos;, &apos;display&apos;, &apos;none&apos;);
        ///		toggleButton(&quot;toggleKeyValues&quot;, &quot;Vis&quot;, &quot;Vis nøgleværdier&quot;);
        ///	} else if (document.getElementById(&quot;toggleKeyValues&quot;).value == &quot;Vis&quot;) {
        ///		var headerHeight [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap middot {
            get {
                object obj = ResourceManager.GetObject("middot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body onload=&quot;loadKeyValueList()&quot;&gt;
        ///  &lt;div id=&quot;header&quot;&gt;
        ///    &lt;div id=&quot;logo&quot;&gt;&lt;/div&gt;
        ///	&lt;h1 id=&quot;logtitle&quot;&gt;LOGFILETITLE&lt;/h1&gt;
        ///	&lt;p id=&quot;generatedbypOvid&quot;&gt;Leveret til dig af Ovid&lt;/p&gt;
        ///  &lt;div id=&quot;buttons&quot;&gt;&lt;button id=&quot;passBtn&quot;          value=&quot;Skjul&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.pass&apos;,  &apos;passBtn&apos;,  &apos;Pass&apos;)&quot; &gt;Skjul Pass&lt;/button&gt;
        ///  &lt;button id=&quot;failBtn&quot;          value=&quot;Skjul&quot; type=&quot;button&quot; onclick=&quot;toggleLogElements(&apos;.fail&apos;,  &apos;failBtn&apos;,  &apos;Fail&apos;)&quot; &gt;Skjul Fail&lt;/button&gt;
        ///  &lt;button id=&quot;errorBtn&quot;         value [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OpenBody {
            get {
                return ResourceManager.GetString("OpenBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to body {
        ///font-family: verdana;
        ///font-size: 1.0em;
        ///color: black;
        ///padding: 0;
        ///margin: 0;
        ///}
        ///h1#logtitle {
        ///font-size: 1.5em;
        ///margin-bottom: 0px;
        ///padding-bottom: 0px;
        ///}
        ///div#logo {
        ///margin-left: 5px;
        ///height: 30px;
        ///width: 101px;
        ///background: url(data:image/x-png;base64,iVBORw0KGgoAAAANSUhEUgAAAGUAAAAeCAYAAAA1mdDNAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKT2lDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVNnVFPpFj333vRCS4iAlEtvUhUIIFJCi4AUkSYqIQkQSoghodkVUcERRUUEG8igiAOOjoCMFVEsDIoK2AfkIaKOg6OIisr74Xuja9a89+bN/rXXPues852zzw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
